---

- name: Create .kube folder
  ansible.builtin.file:
    path: "~/.kube"
    state: directory

- name: Get kubeconfig file
  ansible.builtin.shell: |
    talosctl -n {{ hostvars[groups['control_planes'][0]].ansible_host }} kubeconfig $HOME/.kube/config