---

- name: Install Talos CLI
  ansible.builtin.shell: |
    curl -sL https://talos.dev/install | sh
  when: inventory_hostname == groups['control_planes'][0]

- name: Install FluxCD CLI
  ansible.builtin.shell: |
    curl -s https://fluxcd.io/install.sh | sudo bash
  when: inventory_hostname == groups['control_planes'][0]

- name: Install TalHelper CLI
  ansible.builtin.shell: |
    curl https://i.jpillora.com/budimanjojo/talhelper! | sudo bash
  when: inventory_hostname == groups['control_planes'][0]

- name: Install Cilium CLI
  ansible.builtin.shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
    sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
  when: inventory_hostname == groups['control_planes'][0]

- name: Remove Cilium archive configFiles
  ansible.builtin.file: 
    path: "{{ item }}"
    state: absent
  with_items: 
    - cilium-linux-amd64.tar.gz
    - cilium-linux-amd64.tar.gz.sha256sum
  when: inventory_hostname == groups['control_planes'][0]

